server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog_user
    password: catalog_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
